# Generated by Django 3.1.1 on 2020-11-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='workers',
            field=models.ManyToManyField(to='app.Worker'),
        ),
    ]
