# Generated by Django 3.1.1 on 2020-10-01 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(22, 25, 50, 171728), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='ce7d5c30b0e54ea38cae0fa067c8a287', max_length=30),
        ),
    ]
