# Generated by Django 3.1.1 on 2020-10-01 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201001_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(23, 6, 9, 757872), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='03cb1db9ae2f45a98ef5f5f1ba495780', max_length=30),
        ),
    ]
