# Generated by Django 3.1.1 on 2020-10-01 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201001_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(23, 49, 48, 646133), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='8782418bdb8d4df78ff58bc6ef00250c', max_length=30),
        ),
    ]
