# Generated by Django 3.1.1 on 2020-10-01 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201001_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 0, 3, 14, 365569)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='fc94f9135abc4f5888fe4b538a3b8f5f', max_length=30),
        ),
    ]
