# Generated by Django 3.1.1 on 2020-10-01 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201002_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 0, 5, 0, 415314)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='989ba9104cf8411faf7cb0ef6a3b14f0', max_length=30),
        ),
    ]
