# Generated by Django 3.1.1 on 2020-10-02 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201002_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='C:/static/img/default_avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 13, 17, 58, 949788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='72f5ef06b73a4f63a77486125576e448', max_length=30),
        ),
    ]
