# Generated by Django 3.1.1 on 2020-10-02 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201002_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 13, 20, 59, 437048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='4f2f473d4c194255ab7463102145d1ac', max_length=30),
        ),
    ]
