# Generated by Django 3.1.1 on 2020-10-02 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201002_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(default='activation', max_length=30),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 18, 30, 26, 896241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='72a3a148313d4317ac94e3564e6ea595', max_length=30),
        ),
    ]
