# Generated by Django 3.1.1 on 2020-10-02 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201002_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 20, 19, 53, 968068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='2775cc538977402f9f27f6a927764381', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatars/default_avatar.png', upload_to=''),
        ),
    ]
