# Generated by Django 3.1.1 on 2020-10-02 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201003_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 23, 52, 45, 65587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='7d370111f64f4c23b1d85b59d9007435', max_length=30),
        ),
    ]
