# Generated by Django 3.1.1 on 2020-10-03 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201003_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 0, 50, 12, 99322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='0ea9c2dccc654e518ed639053877703d', max_length=30),
        ),
    ]
