# Generated by Django 3.1.1 on 2020-11-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='serialized_array',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='CardFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.card')),
            ],
        ),
    ]
