# Generated by Django 3.1.1 on 2020-11-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201105_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfile',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.card'),
        ),
    ]
